// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlvqZ3wwl02YlY3yI1HP5JDhH6zWzWl7E',
    appId: '1:1018781468946:web:a4abc5a196f5ed2e6d8bcb',
    messagingSenderId: '1018781468946',
    projectId: 'student-manager-5bf87',
    authDomain: 'student-manager-5bf87.firebaseapp.com',
    storageBucket: 'student-manager-5bf87.firebasestorage.app',
    measurementId: 'G-W2WYE8G7QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtkzSk55-FEn9HdVku0wMWwbsfoRBvvEs',
    appId: '1:1018781468946:android:3656be250dbdc9626d8bcb',
    messagingSenderId: '1018781468946',
    projectId: 'student-manager-5bf87',
    storageBucket: 'student-manager-5bf87.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlvqZ3wwl02YlY3yI1HP5JDhH6zWzWl7E',
    appId: '1:1018781468946:web:c4a53196f45e18816d8bcb',
    messagingSenderId: '1018781468946',
    projectId: 'student-manager-5bf87',
    authDomain: 'student-manager-5bf87.firebaseapp.com',
    storageBucket: 'student-manager-5bf87.firebasestorage.app',
    measurementId: 'G-BEEPEHEHQ3',
  );
}
